# Generated by Django 5.0.6 on 2024-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/buissnesses/")),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("email", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField()),
                ("is_payed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
